server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://db:5432/notifier
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  #email notification settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NF_USERNAME}
    password: ${NF_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 15000
          timeout: 15000
          writetimeout: 15000
          starttls:
            enable: true
          debug: true
  freemarker:
    request-context-attribute: request
    cache: false
    template-loader-path: classpath:/templates/email/
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: classpath:session_tables.sql
  main:
    allow-bean-definition-overriding: true

security:
  oauth2:
    client:
      clientId: ${CLIENT_ID}
      clientSecret: ${CLIENT_SECRET}
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: openid,email,profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true

twilio:
  accountSid: ${TWILIO_ACCOUNT_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  phoneNumber: ${TWILIO_PHONE_NUMBER}